const db=require('../database/db');
const crypto=require('crypto');
function type(id){return db.prepare('SELECT * FROM artifact_types WHERE id=?').get(id)}
function artifact(id){return db.prepare(`SELECT a.*,t.name,t.collection_name,t.discord_role_id,t.theme,t.passive,t.rarity,t.max_copies FROM artifacts a JOIN artifact_types t ON t.id=a.type_id WHERE a.id=?`).get(id)}
function ownsNamed(g,u,name){return Boolean(db.prepare(`SELECT 1 FROM artifacts a JOIN artifact_types t ON t.id=a.type_id WHERE t.guild_id=? AND a.owner_id=? AND lower(t.name)=lower(?) LIMIT 1`).get(g,u,name))}
function owned(g,u){return db.prepare(`SELECT a.*,t.name,t.collection_name,t.discord_role_id,t.theme,t.passive,t.rarity,t.max_copies FROM artifacts a JOIN artifact_types t ON t.id=a.type_id WHERE t.guild_id=? AND a.owner_id=? ORDER BY t.collection_name,t.name,a.copy_number`).all(g,u)}
async function syncRole(guild,userId,roleId){if(!roleId)return;const member=await guild.members.fetch(userId).catch(()=>null);if(!member)return;const still=db.prepare(`SELECT COUNT(*) c FROM artifacts a JOIN artifact_types t ON t.id=a.type_id WHERE a.owner_id=? AND t.discord_role_id=?`).get(userId,roleId).c>0;if(still&&!member.roles.cache.has(roleId))await member.roles.add(roleId,'Artifact ownership').catch(()=>{});if(!still&&member.roles.cache.has(roleId))await member.roles.remove(roleId,'Artifact ownership transferred').catch(()=>{})}
async function transfer(guild,artifactId,to,reason,actor,fromExpected=null){const a=artifact(artifactId);if(!a)throw new Error('Artifact not found');if(fromExpected&&a.owner_id!==fromExpected)throw new Error('Current owner changed');const old=a.owner_id;const txid='TX-'+crypto.randomBytes(5).toString('hex').toUpperCase();db.transaction(()=>{db.prepare('UPDATE artifacts SET owner_id=?,obtained_at=?,trade_count=trade_count+1,locked_trade_id=NULL WHERE id=?').run(to,Date.now(),artifactId);db.prepare('INSERT INTO artifact_history(artifact_id,from_user_id,to_user_id,action,reason,transaction_id,created_at) VALUES(?,?,?,?,?,?,?)').run(artifactId,old,to,'transfer',reason,txid,Date.now());db.prepare(`UPDATE collection_preferences SET user_id=? WHERE artifact_id=?`).run(to,artifactId)})();if(old)await syncRole(guild,old,a.discord_role_id);if(to)await syncRole(guild,to,a.discord_role_id);return {artifact:a,txid,old,to}}
function label(a){return `${a.name} #${String(a.copy_number).padStart(3,'0')}`}
module.exports={type,artifact,owned,ownsNamed,transfer,syncRole,label};
