const {EmbedBuilder}=require('discord.js');const db=require('../database/db');const {getConfig}=require('../utils/config');const eco=require('./economy');
const MIN_DELAY=10*60*1000,MAX_DELAY=25*60*1000,WINDOW=15*1000,CHECK=2000;let timer=null,running=false;
const nextDelay=()=>MIN_DELAY+Math.floor(Math.random()*(MAX_DELAY-MIN_DELAY+1));
function channelFor(g){const id=getConfig(g.id,'token_drop_channel');const c=id&&g.channels.cache.get(id);if(c?.isTextBased()&&c.viewable)return c;return g.channels.cache.find(x=>x?.isTextBased()&&x.viewable&&x.name?.toLowerCase()==='general')||g.systemChannel;}
function activeEmbed(exp){return new EmbedBuilder().setColor(0xff1744).setAuthor({name:'🕷️ DRIPCORE • POWER TOKEN DROP'}).setTitle('🪙 One Power Token Appeared!').setDescription(`Type **/pick** in this channel before anyone else.\n\n⏳ Expires <t:${Math.floor(exp/1000)}:R>\n\n*Buttons are disabled—typing the command helps stop simple auto-clickers.*`).setFooter({text:'Exactly 1 PT • Randomly every 10–25 minutes'}).setTimestamp()}
function closed(title,text,color){return new EmbedBuilder().setColor(color).setTitle(title).setDescription(text).setFooter({text:'Another drop will appear randomly in 10–25 minutes'}).setTimestamp()}
function schedule(gid,when){db.prepare(`INSERT INTO token_drop_state(guild_id,next_drop_at) VALUES(?,?) ON CONFLICT(guild_id) DO UPDATE SET next_drop_at=excluded.next_drop_at`).run(gid,when)}
async function post(g){const ch=channelFor(g);schedule(g.id,Date.now()+nextDelay());if(!ch?.isTextBased())return;const exp=Date.now()+WINDOW;const r=db.prepare(`INSERT INTO token_drops(guild_id,channel_id,amount,status,created_at,expires_at) VALUES(?,?,1,'active',?,?)`).run(g.id,ch.id,Date.now(),exp);const m=await ch.send({embeds:[activeEmbed(exp)]});db.prepare('UPDATE token_drops SET message_id=? WHERE id=?').run(m.id,r.lastInsertRowid)}
async function expire(client,row){const won=db.prepare("UPDATE token_drops SET status='expired' WHERE id=? AND status='active'").run(row.id);if(!won.changes)return;const g=client.guilds.cache.get(row.guild_id),ch=g?.channels.cache.get(row.channel_id),m=await ch?.messages.fetch(row.message_id).catch(()=>null);await m?.edit({embeds:[closed('⌛ Token Drop Expired','Nobody typed **/pick** within 15 seconds.',0x6b7280)]}).catch(()=>{})}
async function tick(client){const now=Date.now();for(const g of client.guilds.cache.values()){const active=db.prepare("SELECT 1 FROM token_drops WHERE guild_id=? AND status='active' AND expires_at>?").get(g.id,now);let s=db.prepare('SELECT * FROM token_drop_state WHERE guild_id=?').get(g.id);if(!s){schedule(g.id,now+nextDelay());continue}if(!active&&s.next_drop_at<=now)await post(g).catch(console.error)}for(const row of db.prepare("SELECT * FROM token_drops WHERE status='active' AND expires_at<=?").all(now))await expire(client,row)}
function start(client){if(timer)return;tick(client);timer=setInterval(()=>{if(running)return;running=true;tick(client).finally(()=>running=false)},CHECK);timer.unref?.()}
async function pick(i){if(!i.inGuild())return i.reply({content:'❌ Use this inside the server.',ephemeral:true});const row=db.prepare("SELECT * FROM token_drops WHERE guild_id=? AND channel_id=? AND status='active' AND expires_at>? ORDER BY id DESC LIMIT 1").get(i.guild.id,i.channel.id,Date.now());if(!row)return i.reply({content:'❌ There is no active token drop in this channel.',ephemeral:true});const tx=db.transaction(()=>{const won=db.prepare("UPDATE token_drops SET status='claimed',winner_id=?,claimed_at=? WHERE id=? AND status='active'").run(i.user.id,Date.now(),row.id);if(!won.changes)return false;eco.add(i.guild.id,i.user.id,1,`Token drop #${row.id}`,'SYSTEM');return true});if(!tx())return i.reply({content:'❌ Someone else picked it first.',ephemeral:true});const m=await i.channel.messages.fetch(row.message_id).catch(()=>null);await m?.edit({embeds:[closed('⚡ Token Drop Claimed!',`${i.user} typed **/pick** first and earned **1 PT**.`,0x22c55e)]}).catch(()=>{});return i.reply({content:'✅ You picked up **1 Power Token**!',ephemeral:true})}
module.exports={start,pick};
