const {SlashCommandBuilder}=require('discord.js');
const db=require('../../database/db');const eco=require('../../services/economy');
const {economyEmbed,COLORS,divider}=require('../../utils/economyTheme');
module.exports={data:new SlashCommandBuilder().setName('tokens').setDescription('Power Token economy')
.addSubcommand(s=>s.setName('balance').setDescription('View a balance').addUserOption(o=>o.setName('user').setDescription('Member')))
.addSubcommand(s=>s.setName('daily').setDescription('Claim your daily Power Tokens'))
.addSubcommand(s=>s.setName('give').setDescription('Owner: give tokens').addUserOption(o=>o.setName('user').setRequired(true).setDescription('Member')).addIntegerOption(o=>o.setName('amount').setRequired(true).setMinValue(1).setDescription('Amount')).addStringOption(o=>o.setName('reason').setDescription('Reason')))
.addSubcommand(s=>s.setName('remove').setDescription('Owner: remove tokens').addUserOption(o=>o.setName('user').setRequired(true).setDescription('Member')).addIntegerOption(o=>o.setName('amount').setRequired(true).setMinValue(1).setDescription('Amount')).addStringOption(o=>o.setName('reason').setDescription('Reason')))
.addSubcommand(s=>s.setName('set').setDescription('Owner: set balance').addUserOption(o=>o.setName('user').setRequired(true).setDescription('Member')).addIntegerOption(o=>o.setName('amount').setRequired(true).setMinValue(0).setDescription('Amount')).addStringOption(o=>o.setName('reason').setDescription('Reason')))
.addSubcommand(s=>s.setName('transfer').setDescription('Send Power Tokens').addUserOption(o=>o.setName('user').setRequired(true).setDescription('Recipient')).addIntegerOption(o=>o.setName('amount').setRequired(true).setMinValue(1).setDescription('Amount'))),
async execute(i){const sub=i.options.getSubcommand(),g=i.guild.id;
 if(sub==='balance'){const u=i.options.getUser('user')||i.user;return i.reply({embeds:[economyEmbed('💠 POWER TOKEN BALANCE',`${divider()}\n${u} controls **${eco.bal(g,u.id)} Power Tokens** across the multiverse.\n${divider()}`,COLORS.neonCyan)],ephemeral:true})}
 if(sub==='daily'){const key='daily',row=db.prepare('SELECT * FROM daily_claims WHERE guild_id=? AND user_id=? AND claim_key=?').get(g,i.user.id,key),now=Date.now();if(row&&now-row.last_claim_at<86400000)return i.reply({embeds:[economyEmbed('⏳ Daily Portal Recharging',`Your next daily claim opens <t:${Math.floor((row.last_claim_at+86400000)/1000)}:R>.`,COLORS.spiderRed)],ephemeral:true});const streak=row&&now-row.last_claim_at<172800000?row.streak+1:1,reward=1;db.prepare(`INSERT INTO daily_claims VALUES(?,?,?,?,?) ON CONFLICT(guild_id,user_id,claim_key) DO UPDATE SET last_claim_at=excluded.last_claim_at,streak=excluded.streak`).run(g,i.user.id,key,now,streak);eco.add(g,i.user.id,reward,'Daily claim','SYSTEM');return i.reply({embeds:[economyEmbed('🕷️ DAILY TOKENS CLAIMED',`${divider()}\n💠 **+${reward} PT**\n🔥 **${streak}-day streak**\n🏦 **Balance: ${eco.bal(g,i.user.id)} PT**\n${divider()}`,COLORS.spiderBlue)],ephemeral:true})}
 if(['give','remove','set'].includes(sub)){if(!eco.isOwner(i))return i.reply({content:'❌ Bot/server owners only.',ephemeral:true});const u=i.options.getUser('user'),a=i.options.getInteger('amount'),r=i.options.getString('reason')||`Owner ${sub}`;if(sub==='set'){const cur=eco.bal(g,u.id);eco.add(g,u.id,a-cur,r,i.user.id)}else eco.add(g,u.id,sub==='give'?a:-a,r,i.user.id);return i.reply({embeds:[economyEmbed('⚙️ TOKEN BALANCE UPDATED',`${u} now has **${eco.bal(g,u.id)} PT**.`,COLORS.neonCyan)],ephemeral:true})}
 const u=i.options.getUser('user'),a=i.options.getInteger('amount');if(u.bot||u.id===i.user.id)return i.reply({content:'❌ Choose another member.',ephemeral:true});if(!eco.spend(g,i.user.id,a,'Token transfer',i.user.id))return i.reply({content:'❌ Not enough tokens.',ephemeral:true});eco.add(g,u.id,a,'Token transfer',i.user.id);return i.reply({embeds:[economyEmbed('🕸️ TOKENS SENT THROUGH THE PORTAL',`Sent **${a} PT** to ${u}.\n\n**Your balance:** ${eco.bal(g,i.user.id)} PT`,COLORS.neonCyan)],ephemeral:true})}};
