const {SlashCommandBuilder}=require('discord.js');const db=require('../../database/db');const arts=require('../../services/artifacts');const h=require('../../handlers/economyHandler');
function reset(id){db.prepare(`UPDATE trades SET ready_a=0,ready_b=0,confirm_a=0,confirm_b=0,status='open',locked_at=NULL WHERE id=?`).run(id)}
module.exports={data:new SlashCommandBuilder().setName('trade').setDescription('Secure two-person artifact swaps')
.addSubcommand(s=>s.setName('start').setDescription('Start a trade').addUserOption(o=>o.setName('user').setRequired(true).setDescription('Trading partner')))
.addSubcommand(s=>s.setName('add-artifact').setDescription('Add an owned artifact').addIntegerOption(o=>o.setName('trade_id').setRequired(true).setDescription('Trade ID')).addIntegerOption(o=>o.setName('artifact_id').setRequired(true).setDescription('Artifact ID')))
.addSubcommand(s=>s.setName('add-tokens').setDescription('Set your token offer').addIntegerOption(o=>o.setName('trade_id').setRequired(true).setDescription('Trade ID')).addIntegerOption(o=>o.setName('amount').setRequired(true).setMinValue(0).setDescription('Amount')))
.addSubcommand(s=>s.setName('remove-artifact').setDescription('Remove an artifact offer').addIntegerOption(o=>o.setName('trade_id').setRequired(true).setDescription('Trade ID')).addIntegerOption(o=>o.setName('artifact_id').setRequired(true).setDescription('Artifact ID')))
.addSubcommand(s=>s.setName('history').setDescription('View recent completed trades')),
async execute(i){const s=i.options.getSubcommand(),g=i.guild.id;if(s==='start'){const u=i.options.getUser('user');if(u.bot||u.id===i.user.id)return i.reply({content:'❌ Choose another member.',ephemeral:true});if(db.prepare(`SELECT 1 FROM trades WHERE guild_id=? AND status IN ('open','locked') AND (user_a IN (?,?) OR user_b IN (?,?))`).get(g,i.user.id,u.id,i.user.id,u.id))return i.reply({content:'❌ One of you already has an active trade.',ephemeral:true});const r=db.prepare(`INSERT INTO trades(guild_id,user_a,user_b,channel_id,created_at) VALUES(?,?,?,?,?)`).run(g,i.user.id,u.id,i.channel.id,Date.now()),t=db.prepare('SELECT * FROM trades WHERE id=?').get(r.lastInsertRowid),m=await i.reply({...h.tradeView(t),fetchReply:true});db.prepare('UPDATE trades SET message_id=? WHERE id=?').run(m.id,t.id);return}if(s==='history'){const x=db.prepare(`SELECT * FROM trades WHERE guild_id=? AND status='completed' AND (user_a=? OR user_b=?) ORDER BY completed_at DESC LIMIT 15`).all(g,i.user.id,i.user.id);return i.reply({content:`📜 **Trade History**\n${x.map(t=>`#${t.id} • <@${t.user_a}> ↔ <@${t.user_b}> • <t:${Math.floor(t.completed_at/1000)}:R>`).join('\n')||'No completed trades.'}`,ephemeral:true})}const id=i.options.getInteger('trade_id'),t=db.prepare(`SELECT * FROM trades WHERE id=? AND guild_id=? AND status IN ('open','locked')`).get(id,g);if(!t)return i.reply({content:'❌ Active trade not found.',ephemeral:true});const side=i.user.id===t.user_a?'a':i.user.id===t.user_b?'b':null;if(!side)return i.reply({content:'❌ Not your trade.',ephemeral:true});if(s==='add-artifact'){const aid=i.options.getInteger('artifact_id'),a=arts.artifact(aid);if(!a||a.owner_id!==i.user.id)return i.reply({content:'❌ You do not own that artifact.',ephemeral:true});if(a.locked_trade_id&&a.locked_trade_id!==id)return i.reply({content:'❌ Artifact is locked elsewhere.',ephemeral:true});db.prepare(`INSERT OR IGNORE INTO trade_items(trade_id,side,item_type,item_id,amount) VALUES(?,?,'artifact',?,0)`).run(id,side,aid);db.prepare('UPDATE artifacts SET locked_trade_id=? WHERE id=?').run(id,aid)}else if(s==='remove-artifact'){const aid=i.options.getInteger('artifact_id');db.prepare(`DELETE FROM trade_items WHERE trade_id=? AND side=? AND item_type='artifact' AND item_id=?`).run(id,side,aid);db.prepare('UPDATE artifacts SET locked_trade_id=NULL WHERE id=? AND locked_trade_id=?').run(aid,id)}else{const a=i.options.getInteger('amount');db.prepare(`INSERT INTO trade_items(trade_id,side,item_type,item_id,amount) VALUES(?,?,'tokens',0,?) ON CONFLICT(trade_id,side,item_type,item_id) DO UPDATE SET amount=excluded.amount`).run(id,side,a)}reset(id);const nt=db.prepare('SELECT * FROM trades WHERE id=?').get(id),m=await i.channel.messages.fetch(t.message_id).catch(()=>null);await m?.edit(h.tradeView(nt));return i.reply({content:'✅ Offer updated. Both ready states were reset.',ephemeral:true})}};
