const { SlashCommandBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle, PermissionFlagsBits }=require('discord.js');
const db=require('../../database/db');const {baseEmbed,successEmbed,errorEmbed}=require('../../utils/embeds');const {getConfig}=require('../../utils/config');
const countries=[['France','🇫🇷'],['Japan','🇯🇵'],['Brazil','🇧🇷'],['Canada','🇨🇦'],['Germany','🇩🇪'],['Italy','🇮🇹'],['Mexico','🇲🇽'],['Australia','🇦🇺'],['South Korea','🇰🇷'],['India','🇮🇳']];
function allowed(i){if(i.member.permissions.has(PermissionFlagsBits.ManageEvents))return true;const ids=JSON.parse(getConfig(i.guild.id,'host_roles_json','[]'));return ids.some(id=>i.member.roles.cache.has(id));}
module.exports={data:new SlashCommandBuilder().setName('minigame').setDescription('Host server minigames')
.addSubcommand(s=>s.setName('flag').setDescription('Guess the flag'))
.addSubcommand(s=>s.setName('country').setDescription('Guess the country from a flag'))
.addSubcommand(s=>s.setName('wheel').setDescription('Open a reaction-style entry wheel').addStringOption(o=>o.setName('title').setDescription('Wheel title')))
.addSubcommand(s=>s.setName('spin').setDescription('Spin an open wheel').addIntegerOption(o=>o.setName('wheel_id').setDescription('Wheel ID').setRequired(true))),
async execute(i){if(!allowed(i))return i.reply({embeds:[errorEmbed('Host Role Required')],ephemeral:true});const sub=i.options.getSubcommand();
if(sub==='flag'||sub==='country'){const [name,flag]=countries[Math.floor(Math.random()*countries.length)];const prompt=sub==='flag'?`Type the flag emoji for **${name}**!`:`What country is this flag?\n# ${flag}`;await i.reply({embeds:[baseEmbed().setTitle('🎮 Mini Game').setDescription(prompt).setFooter({text:'First correct answer wins • 30 seconds'})]});const filter=m=>!m.author.bot&&(sub==='flag'?m.content.trim()===flag:m.content.trim().toLowerCase()===name.toLowerCase());const c=await i.channel.awaitMessages({filter,max:1,time:30000});return i.followUp(c.size?{embeds:[successEmbed('Winner!',`${c.first().author} answered correctly: **${name} ${flag}**`)]}:{embeds:[errorEmbed('Time’s Up',`The answer was **${name} ${flag}**.`)]});}
if(sub==='wheel'){const info=db.prepare(`INSERT INTO wheel_sessions(guild_id,channel_id,host_id,entries_json,status,created_at) VALUES(?,?,?,'[]','open',?)`).run(i.guild.id,i.channel.id,i.user.id,Date.now());const id=info.lastInsertRowid;const row=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`wheel_join:${id}`).setLabel('Join Wheel').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`wheel_leave:${id}`).setLabel('Leave').setStyle(ButtonStyle.Secondary));const msg=await i.reply({embeds:[baseEmbed().setTitle(i.options.getString('title')||'🎡 Prize Wheel').setDescription(`Click **Join Wheel** to enter.\nWheel ID: **${id}**`)],components:[row],fetchReply:true});db.prepare(`UPDATE wheel_sessions SET message_id=? WHERE id=?`).run(msg.id,id);return;}
const id=i.options.getInteger('wheel_id');const w=db.prepare(`SELECT * FROM wheel_sessions WHERE id=? AND guild_id=?`).get(id,i.guild.id);if(!w)return i.reply({embeds:[errorEmbed('Wheel Not Found')],ephemeral:true});const entries=JSON.parse(w.entries_json);if(!entries.length)return i.reply({embeds:[errorEmbed('No Entries')],ephemeral:true});const winner=entries[Math.floor(Math.random()*entries.length)];db.prepare(`UPDATE wheel_sessions SET status='closed' WHERE id=?`).run(id);return i.reply({embeds:[successEmbed('🎡 Wheel Winner',`The wheel selected <@${winner}>!`)]});}}
