const { ActionRowBuilder, ButtonBuilder, ButtonStyle, PermissionFlagsBits, ChannelType } = require('discord.js');
const db = require('../database/db');
const { successEmbed, errorEmbed, baseEmbed, infoEmbed } = require('../utils/embeds');
const { sendLog } = require('../utils/logger');
const { getConfig } = require('../utils/config');

const getGiveaway=db.prepare('SELECT * FROM giveaways WHERE id=?');
const getGiveawayByMessage=db.prepare('SELECT * FROM giveaways WHERE message_id=?');
const updateEnded=db.prepare('UPDATE giveaways SET ended=1,winners_json=? WHERE id=?');
const updateLocked=db.prepare('UPDATE giveaways SET locked=? WHERE id=?');
const dueGiveaways=db.prepare('SELECT * FROM giveaways WHERE ended=0 AND ends_at<=?');
const upsertEntry=db.prepare('INSERT INTO giveaway_entries (giveaway_id,user_id,entries) VALUES (?,?,?) ON CONFLICT(giveaway_id,user_id) DO UPDATE SET entries=excluded.entries');
const getEntry=db.prepare('SELECT * FROM giveaway_entries WHERE giveaway_id=? AND user_id=?');
const allEntries=db.prepare('SELECT * FROM giveaway_entries WHERE giveaway_id=?');
const countEntries=db.prepare('SELECT COUNT(*) c FROM giveaway_entries WHERE giveaway_id=?');
const dueClaims=db.prepare('SELECT * FROM giveaway_claims WHERE claimed=0 AND resolved=0 AND deadline_at<=?');

function entryButton(g){return new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`giveaway_enter:${g.id}`).setLabel('🎉 Enter Giveaway').setStyle(ButtonStyle.Success));}
function claimButton(claimId){return new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`giveaway_claim:${claimId}`).setLabel('Claim Prize').setStyle(ButtonStyle.Success));}
function giveawayEmbed(g){return baseEmbed().setTitle(`🎉 ${g.prize}`).setDescription(`Click below to enter!\n\n**Ends:** <t:${Math.floor(g.ends_at/1000)}:R>\n**Winners:** ${g.winner_count}\n**Hosted by:** <@${g.hosted_by}>\n${g.required_role_id?`**Required Role:** <@&${g.required_role_id}>\n`:''}${g.required_guild_rank?`**Required Guild Role:** ${g.required_guild_rank}\n`:''}\n**Entries:** ${countEntries.get(g.id).c}\n\nConfigured bonus-entry roles apply automatically.`);}
function memberEntries(member){let n=1;for(const r of db.prepare('SELECT * FROM giveaway_bonus_roles WHERE guild_id=?').all(member.guild.id))if(member.roles.cache.has(r.role_id))n+=r.extra_entries;return n;}
async function pickWinners(g){const entries=allEntries.all(g.id),pool=[];for(const e of entries)for(let i=0;i<e.entries;i++)pool.push(e.user_id);const winners=new Set(),unique=new Set(pool);while(winners.size<g.winner_count&&winners.size<unique.size)winners.add(pool[Math.floor(Math.random()*pool.length)]);return [...winners];}
async function claimMinutes(member){let n=Number(getConfig(member.guild.id,'giveaway_default_claim_minutes','10'))||10;for(const r of db.prepare('SELECT * FROM giveaway_claim_time_roles WHERE guild_id=?').all(member.guild.id))if(member.roles.cache.has(r.role_id))n+=r.extra_minutes;return n;}
function autoClaim(member){return db.prepare('SELECT role_id FROM giveaway_auto_claim_roles WHERE guild_id=?').all(member.guild.id).some(r=>member.roles.cache.has(r.role_id));}

async function createWinnerTicket(guild,g,winnerId){const member=await guild.members.fetch(winnerId).catch(()=>null);if(!member)return null;const mins=await claimMinutes(member),auto=autoClaim(member),deadline=Date.now()+mins*60000;const info=db.prepare('INSERT OR REPLACE INTO giveaway_claims (giveaway_id,guild_id,winner_id,deadline_at,claimed,auto_claimed,resolved,created_at) VALUES (?,?,?,?,?,?,0,?)').run(g.id,guild.id,winnerId,deadline,auto?1:0,auto?1:0,Date.now());const claimId=info.lastInsertRowid||db.prepare('SELECT id FROM giveaway_claims WHERE giveaway_id=? AND winner_id=?').get(g.id,winnerId).id;
 const categoryId=getConfig(guild.id,'giveaway_ticket_category'),staffRole=getConfig(guild.id,'giveaway_staff_role');const overwrites=[{id:guild.roles.everyone.id,deny:[PermissionFlagsBits.ViewChannel]},{id:winnerId,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]},{id:guild.members.me.id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ManageChannels]}];if(staffRole)overwrites.push({id:staffRole,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]});
 const channel=await guild.channels.create({name:`gw-${g.id}-${member.user.username}`.toLowerCase().replace(/[^a-z0-9-]/g,'').slice(0,90),type:ChannelType.GuildText,parent:categoryId||undefined,permissionOverwrites:overwrites,reason:`Giveaway #${g.id} winner claim`}).catch(()=>null);if(!channel)return null;db.prepare('UPDATE giveaway_claims SET ticket_channel_id=? WHERE id=?').run(channel.id,claimId);await channel.send({content:`<@${winnerId}>${staffRole?` <@&${staffRole}>`:''}`,embeds:[infoEmbed(auto?'🎉 Prize Auto-Claimed':'🎉 You Won!',`You won **${g.prize}** in giveaway **#${g.id}**.\n${auto?'Your configured role automatically marked this prize claimed.':'Press **Claim Prize** before'} ${auto?'':`<t:${Math.floor(deadline/1000)}:R> or the bot will reroll.`}`)],components:auto?[]:[claimButton(claimId)]});return channel;}

async function endGiveaway(client,id,{reroll=false}={}){const g=getGiveaway.get(id);if(!g)return null;const guild=await client.guilds.fetch(g.guild_id).catch(()=>null);if(!guild)return null;const channel=await guild.channels.fetch(g.channel_id).catch(()=>null);const winners=await pickWinners(g);updateEnded.run(JSON.stringify(winners),id);const text=winners.length?winners.map(x=>`<@${x}>`).join(', '):'No valid entries.';if(channel){await channel.send({embeds:[successEmbed(reroll?'🎉 Giveaway Rerolled!':'🎉 Giveaway Ended!',`**${g.prize}**\n**Winner(s):** ${text}\nWinner claim tickets are created automatically.`)]});if(g.message_id){const m=await channel.messages.fetch(g.message_id).catch(()=>null);if(m)await m.edit({embeds:[giveawayEmbed(g).setTitle(`🎉 [ENDED] ${g.prize}`)],components:[]}).catch(()=>{});}}for(const w of winners)await createWinnerTicket(guild,g,w);await sendLog(guild,'log_channel_mod',{title:reroll?'Giveaway Rerolled':'Giveaway Ended',description:`${g.prize} • ${text}`});return winners;}

async function rerollExpired(client,claim){db.prepare('UPDATE giveaway_claims SET resolved=1 WHERE id=?').run(claim.id);const old=getGiveaway.get(claim.giveaway_id);if(!old)return;db.prepare('DELETE FROM giveaway_entries WHERE giveaway_id=? AND user_id=?').run(old.id,claim.winner_id);const guild=await client.guilds.fetch(claim.guild_id).catch(()=>null);if(claim.ticket_channel_id&&guild){const c=await guild.channels.fetch(claim.ticket_channel_id).catch(()=>null);if(c){await c.send({embeds:[errorEmbed('Claim Time Expired','The prize was not claimed in time. A new winner is being selected.')],components:[]});setTimeout(()=>c.delete().catch(()=>{}),10000);}}const winners=await pickWinners({...old,winner_count:1});if(!winners.length)return;const winner=winners[0];const ch=await guild.channels.fetch(old.channel_id).catch(()=>null);if(ch)await ch.send({embeds:[successEmbed('🎉 Automatic Reroll',`<@${claim.winner_id}> did not claim **${old.prize}** in time.\nNew winner: <@${winner}>`)]});await createWinnerTicket(guild,old,winner);}

async function handleInteraction(i,client){const [action,idRaw]=i.customId.split(':');const id=Number(idRaw);if(action==='giveaway_enter'){const g=getGiveaway.get(id);if(!g)return i.reply({embeds:[errorEmbed('Giveaway Not Found')],ephemeral:true});if(g.ended||g.locked)return i.reply({embeds:[errorEmbed(g.ended?'Giveaway Ended':'Giveaway Locked')],ephemeral:true});if(g.required_role_id&&!i.member.roles.cache.has(g.required_role_id))return i.reply({embeds:[errorEmbed('Not Eligible',`You need <@&${g.required_role_id}>.`)],ephemeral:true});if(g.required_guild_rank){const row=db.prepare('SELECT guild_rank FROM guild_members WHERE guild_id=? AND discord_id=? AND active=1').get(i.guild.id,i.user.id);if(!row||row.guild_rank.toLowerCase()!==g.required_guild_rank.toLowerCase())return i.reply({embeds:[errorEmbed('Not Eligible',`You need the guild role **${g.required_guild_rank}**.`)],ephemeral:true});}const existing=getEntry.get(id,i.user.id);if(existing)return i.reply({embeds:[successEmbed('Already Entered',`You have **${existing.entries}** entries.`)],ephemeral:true});const n=memberEntries(i.member);upsertEntry.run(id,i.user.id,n);return i.reply({embeds:[successEmbed('Entered!',`You have **${n}** entr${n===1?'y':'ies'} based on your configured roles.`)],ephemeral:true});}
 if(action==='giveaway_claim'){const claim=db.prepare('SELECT * FROM giveaway_claims WHERE id=?').get(id);if(!claim||claim.winner_id!==i.user.id)return i.reply({embeds:[errorEmbed('Not Your Claim','Only the selected winner can claim this prize.')],ephemeral:true});if(claim.claimed)return i.reply({embeds:[successEmbed('Already Claimed')],ephemeral:true});if(Date.now()>claim.deadline_at)return i.reply({embeds:[errorEmbed('Claim Time Expired')],ephemeral:true});db.prepare('UPDATE giveaway_claims SET claimed=1,resolved=1 WHERE id=?').run(id);return i.update({embeds:[successEmbed('Prize Claimed!',`<@${i.user.id}> claimed this prize. Staff can now complete delivery in this ticket.`)],components:[]});}}

function startScheduler(client){setInterval(async()=>{for(const g of dueGiveaways.all(Date.now()))await endGiveaway(client,g.id).catch(e=>console.error('[giveaway scheduler]',e));for(const c of dueClaims.all(Date.now()))await rerollExpired(client,c).catch(e=>console.error('[claim scheduler]',e));},15000);}
module.exports={handleInteraction,entryButton,giveawayEmbed,endGiveaway,startScheduler,updateLocked,getGiveawayByMessage};
