const { SlashCommandBuilder, PermissionFlagsBits, EmbedBuilder, ChannelType } = require('discord.js');
const db=require('../../database/db'); const {successEmbed,errorEmbed}=require('../../utils/embeds');
const save=db.prepare(`INSERT INTO saved_embeds(guild_id,name,embed_json,created_by,created_at) VALUES(?,?,?,?,?) ON CONFLICT(guild_id,name) DO UPDATE SET embed_json=excluded.embed_json,created_by=excluded.created_by,created_at=excluded.created_at`);
const get=db.prepare(`SELECT * FROM saved_embeds WHERE guild_id=? AND name=?`); const del=db.prepare(`DELETE FROM saved_embeds WHERE guild_id=? AND name=?`);
function color(v){if(!v)return 0x57F287;const n=parseInt(v.replace('#',''),16);return Number.isFinite(n)?n:0x57F287;}
module.exports={data:new SlashCommandBuilder().setName('embed').setDescription('Create and reuse custom embeds').setDefaultMemberPermissions(PermissionFlagsBits.ManageMessages)
.addSubcommand(s=>s.setName('send').setDescription('Send an embed').addChannelOption(o=>o.setName('channel').setDescription('Destination').addChannelTypes(ChannelType.GuildText).setRequired(true)).addStringOption(o=>o.setName('title').setRequired(true).setDescription('Title')).addStringOption(o=>o.setName('description').setRequired(true).setDescription('Description')).addStringOption(o=>o.setName('color').setDescription('#57F287')).addStringOption(o=>o.setName('image').setDescription('Image URL')).addStringOption(o=>o.setName('footer').setDescription('Footer')).addStringOption(o=>o.setName('save_as').setDescription('Preset name')))
.addSubcommand(s=>s.setName('preset').setDescription('Send a saved embed').addStringOption(o=>o.setName('name').setRequired(true).setDescription('Preset name')).addChannelOption(o=>o.setName('channel').setRequired(true).setDescription('Destination').addChannelTypes(ChannelType.GuildText)))
.addSubcommand(s=>s.setName('delete').setDescription('Delete a saved embed').addStringOption(o=>o.setName('name').setRequired(true).setDescription('Preset name'))),
async execute(i){const sub=i.options.getSubcommand();if(sub==='delete'){del.run(i.guild.id,i.options.getString('name'));return i.reply({embeds:[successEmbed('Embed Deleted')],ephemeral:true});}
if(sub==='preset'){const row=get.get(i.guild.id,i.options.getString('name'));if(!row)return i.reply({embeds:[errorEmbed('Preset Not Found')],ephemeral:true});await i.options.getChannel('channel').send({embeds:[new EmbedBuilder(JSON.parse(row.embed_json))]});return i.reply({embeds:[successEmbed('Embed Sent')],ephemeral:true});}
const data={title:i.options.getString('title'),description:i.options.getString('description'),color:color(i.options.getString('color')),footer:i.options.getString('footer')?{text:i.options.getString('footer')}:undefined,image:i.options.getString('image')?{url:i.options.getString('image')}:undefined,timestamp:new Date().toISOString()};
const name=i.options.getString('save_as');if(name)save.run(i.guild.id,name,JSON.stringify(data),i.user.id,Date.now());await i.options.getChannel('channel').send({embeds:[new EmbedBuilder(data)]});return i.reply({embeds:[successEmbed('Embed Sent',name?`Saved as **${name}**.`:'')],ephemeral:true});}}
