const { SlashCommandBuilder, ChannelType } = require('discord.js');
const db = require('../../database/db');
const { successEmbed, errorEmbed } = require('../../utils/embeds');
const { entryButton, giveawayEmbed, endGiveaway, updateLocked } = require('../../handlers/giveawayHandler');
const insert=db.prepare(`INSERT INTO giveaways (guild_id,channel_id,prize,hosted_by,winner_count,required_role_id,required_guild_rank,ends_at,created_at) VALUES (?,?,?,?,?,?,?,?,?)`);
const get=db.prepare('SELECT * FROM giveaways WHERE id=?');
function duration(v){const m=/^(\d+)\s*(s|m|h|d)$/i.exec(v.trim());return m?Number(m[1])*({s:1000,m:60000,h:3600000,d:86400000}[m[2].toLowerCase()]):null;}
module.exports={data:new SlashCommandBuilder().setName('giveaway').setDescription('Run giveaways')
 .addSubcommand(s=>s.setName('start').setDescription('Start a giveaway; configured role bonuses apply automatically').addStringOption(o=>o.setName('prize').setDescription('Prize').setRequired(true)).addStringOption(o=>o.setName('duration').setDescription('30m, 2h, 1d').setRequired(true)).addChannelOption(o=>o.setName('channel').setDescription('Post channel').addChannelTypes(ChannelType.GuildText)).addIntegerOption(o=>o.setName('winners').setDescription('Winner count').setMinValue(1).setMaxValue(20)).addRoleOption(o=>o.setName('required_role').setDescription('Required Discord role')).addStringOption(o=>o.setName('required_guild_role').setDescription('Required guild role/rank')))
 .addSubcommand(s=>s.setName('end').setDescription('End early').addIntegerOption(o=>o.setName('giveaway_id').setDescription('ID').setRequired(true)))
 .addSubcommand(s=>s.setName('reroll').setDescription('Reroll an ended giveaway').addIntegerOption(o=>o.setName('giveaway_id').setDescription('ID').setRequired(true)))
 .addSubcommand(s=>s.setName('lock').setDescription('Lock/unlock entries').addIntegerOption(o=>o.setName('giveaway_id').setDescription('ID').setRequired(true)).addBooleanOption(o=>o.setName('locked').setDescription('Locked?').setRequired(true))),
 async execute(i,client){const sub=i.options.getSubcommand();if(sub==='start'){const ms=duration(i.options.getString('duration'));if(!ms)return i.reply({embeds:[errorEmbed('Invalid Duration','Use `30m`, `2h`, or `1d`.')],ephemeral:true});const c=i.options.getChannel('channel')||i.channel,prize=i.options.getString('prize'),wc=i.options.getInteger('winners')||1,rr=i.options.getRole('required_role'),gr=i.options.getString('required_guild_role'),info=insert.run(i.guild.id,c.id,prize,i.user.id,wc,rr?.id||null,gr||null,Date.now()+ms,Date.now()),g=get.get(info.lastInsertRowid),msg=await c.send({embeds:[giveawayEmbed(g)],components:[entryButton(g)]});db.prepare('UPDATE giveaways SET message_id=? WHERE id=?').run(msg.id,g.id);return i.reply({embeds:[successEmbed('Giveaway Started',`**#${g.id}** posted in ${c}. Automatic role entries are enabled.`)],ephemeral:true});}
 const id=i.options.getInteger('giveaway_id'),g=get.get(id);if(!g||g.guild_id!==i.guild.id)return i.reply({embeds:[errorEmbed('Not Found')],ephemeral:true});if(sub==='lock'){const locked=i.options.getBoolean('locked');updateLocked.run(locked?1:0,id);return i.reply({embeds:[successEmbed(locked?'Giveaway Locked':'Giveaway Unlocked')],ephemeral:true});}if(sub==='end'){if(g.ended)return i.reply({embeds:[errorEmbed('Already Ended')],ephemeral:true});await i.deferReply({ephemeral:true});await endGiveaway(client,id);return i.editReply({embeds:[successEmbed('Giveaway Ended')]});}if(sub==='reroll'){if(!g.ended)return i.reply({embeds:[errorEmbed('Not Ended Yet')],ephemeral:true});await i.deferReply({ephemeral:true});await endGiveaway(client,id,{reroll:true});return i.editReply({embeds:[successEmbed('Giveaway Rerolled')]});}}
};
