const {SlashCommandBuilder,PermissionFlagsBits,ChannelType}=require('discord.js');const db=require('../../database/db');const {successEmbed,errorEmbed,infoEmbed}=require('../../utils/embeds');const {entryButton,giveawayEmbed,endGiveaway,updateLocked}=require('../../handlers/giveawayHandler');
const get=db.prepare(`SELECT * FROM giveaways WHERE id=?`);const setMsg=db.prepare(`UPDATE giveaways SET message_id=? WHERE id=?`);
function dur(s){const m=/^(\d+)\s*(s|m|h|d)$/i.exec(s||'');return m?Number(m[1])*({s:1000,m:60000,h:3600000,d:86400000}[m[2].toLowerCase()]):null;}
function json(s,f){try{return JSON.parse(s)}catch{return f}}
module.exports={data:new SlashCommandBuilder().setName('giveaway').setDescription('Advanced giveaways') .setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild)
.addSubcommand(s=>s.setName('start').setDescription('Start a giveaway').addStringOption(o=>o.setName('prize').setRequired(true).setDescription('Prize')).addStringOption(o=>o.setName('duration').setRequired(true).setDescription('30m, 2h, 1d')).addChannelOption(o=>o.setName('channel').setDescription('Channel').addChannelTypes(ChannelType.GuildText)).addIntegerOption(o=>o.setName('winners').setDescription('Winners').setMinValue(1).setMaxValue(20)).addRoleOption(o=>o.setName('required_role').setDescription('Required role')).addRoleOption(o=>o.setName('bonus_role').setDescription('Bonus role')).addIntegerOption(o=>o.setName('bonus_entries').setDescription('Extra entries').setMinValue(1)).addStringOption(o=>o.setName('preset').setDescription('Saved preset name')).addStringOption(o=>o.setName('description').setDescription('Custom giveaway text')))
.addSubcommand(s=>s.setName('end').setDescription('End early').addIntegerOption(o=>o.setName('giveaway_id').setRequired(true).setDescription('ID')))
.addSubcommand(s=>s.setName('reroll').setDescription('Reroll').addIntegerOption(o=>o.setName('giveaway_id').setRequired(true).setDescription('ID')))
.addSubcommand(s=>s.setName('lock').setDescription('Lock entries').addIntegerOption(o=>o.setName('giveaway_id').setRequired(true).setDescription('ID')).addBooleanOption(o=>o.setName('locked').setRequired(true).setDescription('Locked')))
.addSubcommand(s=>s.setName('entries').setDescription('Add or remove manual entries').addIntegerOption(o=>o.setName('giveaway_id').setRequired(true).setDescription('ID')).addUserOption(o=>o.setName('user').setRequired(true).setDescription('User')).addIntegerOption(o=>o.setName('amount').setRequired(true).setDescription('Positive or negative').setMinValue(-100).setMaxValue(100)))
.addSubcommand(s=>s.setName('preset-save').setDescription('Save giveaway defaults').addStringOption(o=>o.setName('name').setRequired(true).setDescription('Name')).addIntegerOption(o=>o.setName('default_claim_minutes').setDescription('Default 10').setMinValue(1)).addRoleOption(o=>o.setName('bonus_role').setDescription('Bonus entry role')).addIntegerOption(o=>o.setName('bonus_entries').setDescription('Extra entries').setMinValue(1)).addRoleOption(o=>o.setName('claim_bonus_role').setDescription('Longer claim role')).addIntegerOption(o=>o.setName('claim_bonus_minutes').setDescription('Claim minutes')).addRoleOption(o=>o.setName('auto_claim_role').setDescription('Auto ticket + claimed role')).addChannelOption(o=>o.setName('ticket_category').setDescription('Claim ticket category').addChannelTypes(ChannelType.GuildCategory)))
.addSubcommand(s=>s.setName('preset-view').setDescription('View a preset').addStringOption(o=>o.setName('name').setRequired(true).setDescription('Name'))),
async execute(i,client){const sub=i.options.getSubcommand();if(sub==='preset-save'){const name=i.options.getString('name');const settings={defaultClaimMinutes:i.options.getInteger('default_claim_minutes')||10,bonusRoles:i.options.getRole('bonus_role')?[{roleId:i.options.getRole('bonus_role').id,extra:i.options.getInteger('bonus_entries')||1}]:[],claimBonusRoles:i.options.getRole('claim_bonus_role')?[{roleId:i.options.getRole('claim_bonus_role').id,minutes:i.options.getInteger('claim_bonus_minutes')||30}]:[],autoClaimRoles:i.options.getRole('auto_claim_role')?[i.options.getRole('auto_claim_role').id]:[],ticketCategoryId:i.options.getChannel('ticket_category')?.id||null,autoReroll:true};db.prepare(`INSERT INTO giveaway_presets(guild_id,name,settings_json,created_by,created_at) VALUES(?,?,?,?,?) ON CONFLICT(guild_id,name) DO UPDATE SET settings_json=excluded.settings_json,created_by=excluded.created_by,created_at=excluded.created_at`).run(i.guild.id,name,JSON.stringify(settings),i.user.id,Date.now());return i.reply({embeds:[successEmbed('Preset Saved',`Saved **${name}**.`)],ephemeral:true});}
if(sub==='preset-view'){const p=db.prepare(`SELECT * FROM giveaway_presets WHERE guild_id=? AND name=?`).get(i.guild.id,i.options.getString('name'));return i.reply({embeds:[p?infoEmbed(`Preset: ${p.name}`,`
\`\`\`json\n${JSON.stringify(JSON.parse(p.settings_json),null,2).slice(0,3500)}\n\`\`\``):errorEmbed('Preset Not Found')],ephemeral:true});}
const id=i.options.getInteger('giveaway_id');if(sub==='end'||sub==='reroll'){if(!get.get(id))return i.reply({embeds:[errorEmbed('Giveaway Not Found')],ephemeral:true});await i.deferReply({ephemeral:true});await endGiveaway(client,id,{reroll:sub==='reroll'});return i.editReply({embeds:[successEmbed(sub==='reroll'?'Rerolled':'Ended')]});}
if(sub==='lock'){updateLocked.run(i.options.getBoolean('locked')?1:0,id);return i.reply({embeds:[successEmbed('Giveaway Updated')],ephemeral:true});}
if(sub==='entries'){const g=get.get(id);if(!g)return i.reply({embeds:[errorEmbed('Giveaway Not Found')],ephemeral:true});const user=i.options.getUser('user'),amount=i.options.getInteger('amount');const row=db.prepare(`SELECT * FROM giveaway_entries WHERE giveaway_id=? AND user_id=?`).get(id,user.id);const next=Math.max(0,(row?.entries||0)+amount);db.prepare(`INSERT INTO giveaway_entries(giveaway_id,user_id,entries) VALUES(?,?,?) ON CONFLICT(giveaway_id,user_id) DO UPDATE SET entries=excluded.entries`).run(id,user.id,next);return i.reply({embeds:[successEmbed('Entries Updated',`${user} now has **${next}** entries.`)],ephemeral:true});}
const duration=dur(i.options.getString('duration'));if(!duration)return i.reply({embeds:[errorEmbed('Invalid Duration','Use 30m, 2h, or 1d.')],ephemeral:true});const channel=i.options.getChannel('channel')||i.channel;const presetName=i.options.getString('preset');const preset=presetName?db.prepare(`SELECT * FROM giveaway_presets WHERE guild_id=? AND name=?`).get(i.guild.id,presetName):null;const settings=preset?json(preset.settings_json,{}):{};if(i.options.getRole('bonus_role'))settings.bonusRoles=[{roleId:i.options.getRole('bonus_role').id,extra:i.options.getInteger('bonus_entries')||1}];
const info=db.prepare(`INSERT INTO giveaways(guild_id,channel_id,prize,description,hosted_by,winner_count,required_role_id,bonus_roles_json,claim_settings_json,ticket_settings_json,preset_name,ends_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(i.guild.id,channel.id,i.options.getString('prize'),i.options.getString('description'),i.user.id,i.options.getInteger('winners')||1,i.options.getRole('required_role')?.id||null,JSON.stringify(settings.bonusRoles||[]),JSON.stringify({defaultClaimMinutes:settings.defaultClaimMinutes||10,claimBonusRoles:settings.claimBonusRoles||[],autoClaimRoles:settings.autoClaimRoles||[],autoReroll:settings.autoReroll!==false}),JSON.stringify({ticketCategoryId:settings.ticketCategoryId||null}),presetName,Date.now()+duration,Date.now());const g=get.get(info.lastInsertRowid);const msg=await channel.send({embeds:[giveawayEmbed(g)],components:[entryButton(g)]});setMsg.run(msg.id,g.id);return i.reply({embeds:[successEmbed('Giveaway Started',`Giveaway **#${g.id}** posted in ${channel}.`)],ephemeral:true});}}
