const { SlashCommandBuilder, PermissionFlagsBits, ChannelType } = require('discord.js');
const db = require('../../database/db');
const { successEmbed, infoEmbed } = require('../../utils/embeds');
const { setConfig } = require('../../utils/config');

const bonusUpsert=db.prepare('INSERT INTO giveaway_bonus_roles (guild_id,role_id,extra_entries) VALUES (?,?,?) ON CONFLICT(guild_id,role_id) DO UPDATE SET extra_entries=excluded.extra_entries');
const claimUpsert=db.prepare('INSERT INTO giveaway_claim_time_roles (guild_id,role_id,extra_minutes) VALUES (?,?,?) ON CONFLICT(guild_id,role_id) DO UPDATE SET extra_minutes=excluded.extra_minutes');
const autoAdd=db.prepare('INSERT OR IGNORE INTO giveaway_auto_claim_roles (guild_id,role_id) VALUES (?,?)');

module.exports={
 data:new SlashCommandBuilder().setName('giveaway-config').setDescription('Configure automatic giveaway entries and claim tickets').setDefaultMemberPermissions(PermissionFlagsBits.Administrator)
 .addSubcommandGroup(g=>g.setName('bonus-role').setDescription('Automatic bonus entries').addSubcommand(s=>s.setName('add').setDescription('Add/update a bonus role').addRoleOption(o=>o.setName('role').setDescription('Role').setRequired(true)).addIntegerOption(o=>o.setName('extra_entries').setDescription('Extra entries').setMinValue(1).setMaxValue(100).setRequired(true))).addSubcommand(s=>s.setName('remove').setDescription('Remove a bonus role').addRoleOption(o=>o.setName('role').setDescription('Role').setRequired(true))).addSubcommand(s=>s.setName('list').setDescription('List bonus roles')))
 .addSubcommandGroup(g=>g.setName('claim-time').setDescription('Extra claim time by role').addSubcommand(s=>s.setName('add').setDescription('Add/update extra claim time').addRoleOption(o=>o.setName('role').setDescription('Role').setRequired(true)).addIntegerOption(o=>o.setName('extra_minutes').setDescription('Extra minutes').setMinValue(1).setMaxValue(10080).setRequired(true))).addSubcommand(s=>s.setName('remove').setDescription('Remove a claim-time role').addRoleOption(o=>o.setName('role').setDescription('Role').setRequired(true))).addSubcommand(s=>s.setName('list').setDescription('List claim-time roles')))
 .addSubcommandGroup(g=>g.setName('auto-claim').setDescription('Roles whose winner ticket is automatically marked claimed').addSubcommand(s=>s.setName('add').setDescription('Add auto-claim role').addRoleOption(o=>o.setName('role').setDescription('Role').setRequired(true))).addSubcommand(s=>s.setName('remove').setDescription('Remove auto-claim role').addRoleOption(o=>o.setName('role').setDescription('Role').setRequired(true))).addSubcommand(s=>s.setName('list').setDescription('List auto-claim roles')))
 .addSubcommand(s=>s.setName('default-time').setDescription('Set default winner claim time').addIntegerOption(o=>o.setName('minutes').setDescription('Default minutes, normally 10').setMinValue(1).setMaxValue(10080).setRequired(true)))
 .addSubcommand(s=>s.setName('ticket-category').setDescription('Set category for automatic winner tickets').addChannelOption(o=>o.setName('category').setDescription('Category').addChannelTypes(ChannelType.GuildCategory).setRequired(true)))
 .addSubcommand(s=>s.setName('staff-role').setDescription('Set staff role that can see winner tickets').addRoleOption(o=>o.setName('role').setDescription('Staff role').setRequired(true)))
 .addSubcommand(s=>s.setName('manager-role').setDescription('Set giveaway manager role pinged on escalations').addRoleOption(o=>o.setName('role').setDescription('Giveaway manager role').setRequired(true)))
 .addSubcommand(s=>s.setName('view').setDescription('View all giveaway configuration')),
 async execute(i){const gid=i.guild.id, group=i.options.getSubcommandGroup(false), sub=i.options.getSubcommand();
  if(group==='bonus-role'){const role=i.options.getRole('role');if(sub==='add'){const n=i.options.getInteger('extra_entries');bonusUpsert.run(gid,role.id,n);return i.reply({embeds:[successEmbed('Bonus Role Saved',`${role} automatically gets **+${n} entries** in every giveaway.`)],ephemeral:true});}if(sub==='remove'){db.prepare('DELETE FROM giveaway_bonus_roles WHERE guild_id=? AND role_id=?').run(gid,role.id);return i.reply({embeds:[successEmbed('Bonus Role Removed')],ephemeral:true});}const rows=db.prepare('SELECT * FROM giveaway_bonus_roles WHERE guild_id=?').all(gid);return i.reply({embeds:[infoEmbed('Automatic Bonus Entries',rows.length?rows.map(r=>`<@&${r.role_id}> → +${r.extra_entries}`).join('\n'):'None configured.')],ephemeral:true});}
  if(group==='claim-time'){const role=i.options.getRole('role');if(sub==='add'){const n=i.options.getInteger('extra_minutes');claimUpsert.run(gid,role.id,n);return i.reply({embeds:[successEmbed('Claim Time Saved',`${role} gets **+${n} minutes** to claim.`)],ephemeral:true});}if(sub==='remove'){db.prepare('DELETE FROM giveaway_claim_time_roles WHERE guild_id=? AND role_id=?').run(gid,role.id);return i.reply({embeds:[successEmbed('Claim Time Removed')],ephemeral:true});}const rows=db.prepare('SELECT * FROM giveaway_claim_time_roles WHERE guild_id=?').all(gid);return i.reply({embeds:[infoEmbed('Claim-Time Roles',rows.length?rows.map(r=>`<@&${r.role_id}> → +${r.extra_minutes} minutes`).join('\n'):'None configured.')],ephemeral:true});}
  if(group==='auto-claim'){const role=i.options.getRole('role');if(sub==='add'){autoAdd.run(gid,role.id);return i.reply({embeds:[successEmbed('Auto-Claim Role Added',`${role} winner tickets will open already marked claimed.`)],ephemeral:true});}if(sub==='remove'){db.prepare('DELETE FROM giveaway_auto_claim_roles WHERE guild_id=? AND role_id=?').run(gid,role.id);return i.reply({embeds:[successEmbed('Auto-Claim Role Removed')],ephemeral:true});}const rows=db.prepare('SELECT * FROM giveaway_auto_claim_roles WHERE guild_id=?').all(gid);return i.reply({embeds:[infoEmbed('Auto-Claim Roles',rows.length?rows.map(r=>`<@&${r.role_id}>`).join('\n'):'None configured.')],ephemeral:true});}
  if(sub==='default-time'){const n=i.options.getInteger('minutes');setConfig(gid,'giveaway_default_claim_minutes',n);return i.reply({embeds:[successEmbed('Default Claim Time Updated',`Winners get **${n} minutes** before an automatic reroll.`)],ephemeral:true});}
  if(sub==='ticket-category'){const c=i.options.getChannel('category');setConfig(gid,'giveaway_ticket_category',c.id);return i.reply({embeds:[successEmbed('Winner Ticket Category Set',`${c}`)],ephemeral:true});}
  if(sub==='staff-role'){const r=i.options.getRole('role');setConfig(gid,'giveaway_staff_role',r.id);return i.reply({embeds:[successEmbed('Giveaway Staff Role Set',`${r}`)],ephemeral:true});}
  if(sub==='manager-role'){const r=i.options.getRole('role');setConfig(gid,'giveaway_manager_role',r.id);return i.reply({embeds:[successEmbed('Giveaway Manager Role Set',`${r}`)],ephemeral:true});}
  const bonus=db.prepare('SELECT * FROM giveaway_bonus_roles WHERE guild_id=?').all(gid), times=db.prepare('SELECT * FROM giveaway_claim_time_roles WHERE guild_id=?').all(gid), auto=db.prepare('SELECT * FROM giveaway_auto_claim_roles WHERE guild_id=?').all(gid);return i.reply({embeds:[infoEmbed('Giveaway Configuration',`**Bonus roles:** ${bonus.length}\n**Claim-time roles:** ${times.length}\n**Auto-claim roles:** ${auto.length}\nUse the other subcommands to view details.`)],ephemeral:true});
 }
};
