const { SlashCommandBuilder, PermissionFlagsBits, ChannelType } = require('discord.js');
const { setConfig, getConfig, deleteConfig } = require('../../utils/config');
const { successEmbed, infoEmbed } = require('../../utils/embeds');
module.exports={data:new SlashCommandBuilder().setName('ai').setDescription('Configure DripCore mention responses').setDefaultMemberPermissions(PermissionFlagsBits.Administrator)
 .addSubcommand(s=>s.setName('enable').setDescription('Enable AI mention replies'))
 .addSubcommand(s=>s.setName('disable').setDescription('Disable AI mention replies'))
 .addSubcommand(s=>s.setName('set-info').setDescription('Set server rules, guild requirements, giveaway instructions, and FAQs').addStringOption(o=>o.setName('information').setDescription('Information the bot is allowed to use').setMaxLength(4000).setRequired(true)))
 .addSubcommand(s=>s.setName('add-info').setDescription('Append information to the knowledge base').addStringOption(o=>o.setName('information').setDescription('New approved information').setMaxLength(2000).setRequired(true)))
 .addSubcommand(s=>s.setName('clear-info').setDescription('Clear the AI knowledge base'))
 .addSubcommand(s=>s.setName('set-help-channel').setDescription('Channel for help guidance').addChannelOption(o=>o.setName('channel').setDescription('Help channel').addChannelTypes(ChannelType.GuildText).setRequired(true)))
 .addSubcommand(s=>s.setName('set-guild-channel').setDescription('Channel for guild joining').addChannelOption(o=>o.setName('channel').setDescription('Guild channel').addChannelTypes(ChannelType.GuildText).setRequired(true)))
 .addSubcommand(s=>s.setName('set-giveaway-channel').setDescription('Channel for giveaways').addChannelOption(o=>o.setName('channel').setDescription('Giveaway channel').addChannelTypes(ChannelType.GuildText).setRequired(true)))
 .addSubcommand(s=>s.setName('set-staff-role').setDescription('Staff role to mention for escalation').addRoleOption(o=>o.setName('role').setDescription('Staff role').setRequired(true)))
 .addSubcommand(s=>s.setName('view').setDescription('View AI configuration')),
 async execute(i){const sub=i.options.getSubcommand(),gid=i.guild.id;if(sub==='enable'||sub==='disable'){setConfig(gid,'ai_enabled',sub==='enable'?'true':'false');return i.reply({embeds:[successEmbed(`AI ${sub==='enable'?'Enabled':'Disabled'}`)],ephemeral:true});}if(sub==='set-info'){setConfig(gid,'ai_knowledge',i.options.getString('information'));return i.reply({embeds:[successEmbed('AI Information Saved')],ephemeral:true});}if(sub==='add-info'){const old=getConfig(gid,'ai_knowledge','');setConfig(gid,'ai_knowledge',`${old}\n${i.options.getString('information')}`.trim().slice(0,12000));return i.reply({embeds:[successEmbed('AI Information Added')],ephemeral:true});}if(sub==='clear-info'){deleteConfig(gid,'ai_knowledge');return i.reply({embeds:[successEmbed('AI Information Cleared')],ephemeral:true});}const map={'set-help-channel':'ai_help_channel','set-guild-channel':'ai_guild_channel','set-giveaway-channel':'ai_giveaway_channel'};if(map[sub]){const c=i.options.getChannel('channel');setConfig(gid,map[sub],c.id);return i.reply({embeds:[successEmbed('AI Channel Saved',`${c}`)],ephemeral:true});}if(sub==='set-staff-role'){const r=i.options.getRole('role');setConfig(gid,'ai_staff_role',r.id);return i.reply({embeds:[successEmbed('AI Staff Role Saved',`${r}`)],ephemeral:true});}return i.reply({embeds:[infoEmbed('AI Configuration',`**Enabled:** ${getConfig(gid,'ai_enabled','false')}\n**Knowledge:** ${getConfig(gid,'ai_knowledge','').length} characters\n**Help:** ${getConfig(gid,'ai_help_channel')?`<#${getConfig(gid,'ai_help_channel')}>`:'Not set'}\n**Guild:** ${getConfig(gid,'ai_guild_channel')?`<#${getConfig(gid,'ai_guild_channel')}>`:'Not set'}\n**Giveaways:** ${getConfig(gid,'ai_giveaway_channel')?`<#${getConfig(gid,'ai_giveaway_channel')}>`:'Not set'}\n**Staff:** ${getConfig(gid,'ai_staff_role')?`<@&${getConfig(gid,'ai_staff_role')}>`:'Not set'}\n\nSet \`OPENAI_API_KEY\` in Railway for full AI chat. Without it, DripCore uses safe built-in guidance.`)],ephemeral:true});}
};
